#!/usr/bin/env ruby
FIXED_GEMS = %w(rails pg paginate serializer rubocop simplecov factory_bot rspec rack-cors listen)

def qa(str)
  puts str
  res = STDIN.gets.chomp
  return true if res.casecmp('Y')
  return false if res.casecmp('N')

  qa('Please answer with Y(yes) or N(no)')
end

def remove_gem_config(gem_name)
  config_name = gem_name.gsub('-','_').partition('_').first
  config_files = Dir["config/initializers/*"].select { |filename| filename.include?(config_name) }
  config_files.each { |file| File.delete(file) }
  if config_name.casecmp('Sidekiq')
    out = File.read('config/routes.rb').gsub("mount Sidekiq::Web, at: 'sidekiq'\n", '')
    File.open('config/routes.rb', 'w') { |file| file.puts(out) }
  end
end

# Changes App name
app_name = ARGV.first
system('rm -rf tmp')
system('rm -rf log')
system('rm -rf .travis.yml')
system('rm -rf config/database.travis.yml')
system('rm -rf coverage')
puts "Setting App name: #{app_name}..."
Dir.glob('**/*', File::FNM_DOTMATCH).reject { |f| f['.git'] || f['script'] }.each do |name|
  next unless File.file?(name) && name != '.DS_Store'
  out = File.read(name).gsub('rails-bootstrap', app_name)
  out = out.gsub('RailsBootstrap', app_name.tr('-', '_').split('_').map(&:capitalize).join)
  File.open(name, 'w+') do |f|
    f << out
  end
end

# User selects which gems they want to keep
response = qa('Do you wish to exclude some of the standard bootstrap gems? Y/N')
if response
  file = File.read('Gemfile')
  lines = file.split("\n").select { |line| line.start_with?('gem', '  gem') }
  gems = lines.reject { |line| FIXED_GEMS.any? { |gem| line.include?(gem) } }
  gems.each do |gem|
    lindex = gem.index("'") + 1
    rindex = gem.enum_for(:scan, /(?=')/).map { Regexp.last_match.offset(0).first }[1]
    gem_name = gem[lindex, rindex - lindex]
    next unless qa("Remove #{gem_name}? Y/N")
    file.gsub!(gem, '')
    remove_gem_config
  end
  file = file.split("\n\n\n").reject { |a| a.empty? }.join("\n")
  File.open('Gemfile', 'w') { |gemfile| gemfile.puts(file) }
end

# Removes Gitter and LICENSE
readme = File.read('README.md')
readme.gsub!(
  '[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Wolox' \
  '/rails-bootstrap?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_' \
  "content=badge)\n",
  ''
)
readme.gsub!('Kickoff for Rails web applications.', '')
readme.gsub!('### Application Setup', '')
readme.gsub!('Run `./script/bootstrap app_name` where `app_name` is your application name.', '')
readme.gsub!("\n\n\n\n\n\nYour app is ready. Happy coding!", '')
readme.gsub!(/\n\n## License((.)*(\n)*)*$/, '')
File.open('README.md', 'w') { |file| file.puts(readme) }
File.delete('LICENSE')

puts 'Done'
